In [1]:
# Imports and load raw data

import pandas as pd
import numpy as np

df = pd.read_csv("../data/Raw datasets/All_type_of_EV_registration.csv")

print("Chargers shape:", df.shape)
df.head(37)

Chargers shape: (37, 12)

,"EV Type (ELECTRIC(BOV), PURE EV) Wise State Wise and Calendar Year Data for AN, AP, AR, AS, BR, CH, CG, DL, GA, GJ, HR, HP, JK, JH, KA, KL, LA, LD, MP, MH, MN, ML, MZ, NL, OR, PY, PB, RJ, SK, TN, TG, TR, DD, UP, UK, WB (2017-2026)\n\nState",2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,Total
0,Andaman & Nicobar Island,0,20,2,36,92,23,26,64,166,117,546
1,Andhra Pradesh,1,1180,2155,1650,9681,29357,32876,56492,59842,85267,278501
2,Arunachal Pradesh,0,1,1,4,2,2,18,47,103,136,314
3,Assam,3831,7398,10859,8357,15633,40697,60786,68130,85142,83467,384300
4,Bihar,3594,8464,12380,12446,23083,55755,88223,112856,123797,119840,560438
5,Chandigarh,23,213,508,369,729,2720,6390,6182,5180,5105,27419
6,Chhattisgarh,944,1903,2744,1489,4216,22361,38245,48859,47735,48029,216525
7,Delhi,17846,20902,23221,12374,25792,62225,73721,80388,113758,85670,515897
8,Goa,36,25,42,82,1100,5687,9485,11491,9367,9865,47180
9,Gujarat,173,500,947,1124,9761,68994,88617,75759,75779,94188,415842
10,Haryana,2489,4625,5107,2980,8664,25844,30599,43005,37391,30600,191304
11,Himachal Pradesh,16,62,54,181,326,1016,1144,1765,1935,2138,8637
12,Jammu and Kashmir,0,90,75,74,1147,4690,9752,13212,11827,13348,54215
13,Jharkhand,1353,1957,1932,1516,3740,13681,21124,25979,34028,34540,139850
14,Karnataka,709,2262,6138,9682,33275,95772,152701,179209,203693,229043,912484
15,Kerala,77,299,530,1376,8737,39645,75824,83271,106975,116758,433492
16,Ladakh,0,0,1,0,6,40,28,18,3,8,104
17,Lakshadweep,0,0,1,7,5,2,9,15,32,73,144
18,Madhya Pradesh,1409,2741,3684,3362,10446,36818,67976,100477,139920,146170,513003
19,Maharashtra,906,4631,7323,7124,29903,135964,194165,241808,266556,282093,1170473
20,Manipur,5,39,251,102,114,341,399,422,1199,1243,4115
21,Meghalaya,0,2,13,3,5,41,115,798,945,700,2622
22,Mizoram,0,0,1,1,1,36,168,560,825,1032,2624
23,Nagaland,0,1,31,12,2,3,6,13,23,25,116
24,Odisha,212,1358,1160,903,5626,28443,44542,65307,79234,114855,341640
25,Puducherry,9,87,81,89,406,1483,2637,4512,4606,5847,19757
26,Punjab,137,365,961,832,4650,14056,25754,44467,45273,45433,181928
27,Rajasthan,3948,4677,6635,5613,23479,78284,93816,109375,114453,128816,569096
28,Sikkim,0,0,0,0,0,0,0,7,9,13,29
29,Tamil Nadu,109,1340,3461,5696,30047,67024,90250,131452,166224,213157,708760
30,Telangana,74,928,1034,1323,9646,34556,50345,75636,83772,100606,357920
31,Tripura,2,32,1459,3419,2432,4177,6311,9614,10229,7546,45221
32,UT of DNH and DD,1,19,19,24,28,142,160,338,300,268,1299
33,Uttar Pradesh,40645,53199,55786,31256,66688,162879,278296,369283,405364,352096,1815492
34,Uttarakhand,4224,5067,5817,2392,5320,15560,16801,19834,20243,19631,114889
35,West Bengal,4452,6728,13533,10079,6406,11147,21427,45630,100946,121296,341644
36,Total,87225,131115,167946,125977,341188,1059465,1582736,2026275,2356874,2499019,10377820

In [2]:
# Create a working copy

ev_df = df.copy()

print("Original shape:", df.shape)
print("Working copy shape:", ev_df.shape)

Original shape: (37, 12)
Working copy shape: (37, 12)

In [3]:
# Check column names

print(ev_df.columns.tolist())

['EV Type (ELECTRIC(BOV), PURE EV) Wise State Wise and Calendar Year Data for AN, AP, AR, AS, BR, CH, CG, DL, GA, GJ, HR, HP, JK, JH, KA, KL, LA, LD, MP, MH, MN, ML, MZ, NL, OR, PY, PB, RJ, SK, TN, TG, TR, DD, UP, UK, WB (2017-2026)\\n\\nState', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025', '2026', 'Total']

In [4]:
# CELL 4: Rename the state column

ev_df = ev_df.rename(columns={
    ev_df.columns[0]: "State"
})

print(ev_df.columns.tolist())

['State', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025', '2026', 'Total']

In [5]:
# Check State values

print(ev_df["State"].tolist())

['Andaman & Nicobar Island', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Ladakh', 'Lakshadweep', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'UT of DNH and DD', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal', 'Total']

In [6]:
# Remove Total row

ev_df = ev_df[ev_df["State"] != "Total"].copy()

print("Shape after removing Total row:", ev_df.shape)
ev_df["State"].tail()

Shape after removing Total row: (36, 12)

31             Tripura
32    UT of DNH and DD
33       Uttar Pradesh
34         Uttarakhand
35         West Bengal
Name: State, dtype: str

In [7]:
# Check duplicate states

print("Duplicate state names:", ev_df["State"].duplicated().sum())

print("\nDuplicate states:")
print(ev_df[ev_df["State"].duplicated(keep=False)]["State"])

Duplicate state names: 0

Duplicate states:
Series([], Name: State, dtype: str)

In [8]:
# Check missing values

print(ev_df.isnull().sum())

State    0
2017     0
2018     0
2019     0
2020     0
2021     0
2022     0
2023     0
2024     0
2025     0
2026     0
Total    0
dtype: int64

In [9]:
# Check data types

print(ev_df.dtypes)

State      str
2017     int64
2018     int64
2019     int64
2020     int64
2021     int64
2022     int64
2023     int64
2024     int64
2025     int64
2026     int64
Total    int64
dtype: object

In [10]:
# Check for negative values

numeric_cols = ev_df.columns[1:]

print((ev_df[numeric_cols] < 0).sum())

2017     0
2018     0
2019     0
2020     0
2021     0
2022     0
2023     0
2024     0
2025     0
2026     0
Total    0
dtype: int64

In [11]:
# Validate Total column

year_cols = [str(year) for year in range(2017, 2027)]

calculated_total = ev_df[year_cols].sum(axis=1)

print("Rows where Total does not match calculated total:",
      (ev_df["Total"] != calculated_total).sum())

Rows where Total does not match calculated total: 0

In [12]:
# Check duplicate rows

print("Duplicate rows:", ev_df.duplicated().sum())

Duplicate rows: 0

In [13]:
# Check whitespace in State names

print(
    "States with leading/trailing whitespace:",
    (~ev_df["State"].eq(ev_df["State"].str.strip())).sum()
)

States with leading/trailing whitespace: 0

In [14]:
# Check blank State values

print(
    "Blank State values:",
    ev_df["State"].str.strip().eq("").sum()
)

Blank State values: 0

In [15]:
# Check zero values

print((ev_df[year_cols] == 0).sum())

2017    9
2018    4
2019    1
2020    2
2021    1
2022    1
2023    1
2024    0
2025    0
2026    0
dtype: int64

In [16]:
# Identify zero registration values

zero_check = ev_df[year_cols].eq(0)

display(ev_df.loc[zero_check.any(axis=1), ["State"] + year_cols].reset_index(drop=True))

,State,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026
0,Andaman & Nicobar Island,0,20,2,36,92,23,26,64,166,117
1,Arunachal Pradesh,0,1,1,4,2,2,18,47,103,136
2,Jammu and Kashmir,0,90,75,74,1147,4690,9752,13212,11827,13348
3,Ladakh,0,0,1,0,6,40,28,18,3,8
4,Lakshadweep,0,0,1,7,5,2,9,15,32,73
5,Meghalaya,0,2,13,3,5,41,115,798,945,700
6,Mizoram,0,0,1,1,1,36,168,560,825,1032
7,Nagaland,0,1,31,12,2,3,6,13,23,25
8,Sikkim,0,0,0,0,0,0,0,7,9,13

In [17]:
# Check duplicate column names

print("Duplicate column names:", ev_df.columns.duplicated().sum())

Duplicate column names: 0

In [18]:
# Check unique state count

print("Number of states/UTs:", ev_df["State"].nunique())

Number of states/UTs: 36

In [19]:
ev_df.describe()

,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,Total
count,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,3.600000e+01
mean,2422.916667,3642.083333,4665.166667,3499.361111,9477.444444,29429.583333,43964.888889,56285.416667,65468.722222,69417.194444,2.882728e+05
std,7274.896564,9377.834829,10093.569553,6036.636922,13956.920175,39576.280703,61199.329325,77784.073867,87882.861634,87779.446377,3.884789e+05
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000,3.000000,8.000000,2.900000e+01
25%,0.750000,23.750000,39.250000,64.500000,108.500000,291.250000,341.250000,738.500000,1135.500000,1190.250000,3.742250e+03
50%,75.500000,432.500000,997.500000,1223.500000,4433.000000,13868.500000,21275.500000,34492.000000,35709.500000,32570.000000,1.608890e+05
75%,1367.000000,3212.000000,5284.500000,3967.500000,9932.250000,39908.000000,69412.250000,76916.250000,102453.250000,115330.750000,4.202545e+05
max,40645.000000,53199.000000,55786.000000,31256.000000,66688.000000,162879.000000,278296.000000,369283.000000,405364.000000,352096.000000,1.815492e+06

In [20]:
# Save cleaned dataset

clean_path = "../data/Cleaned datasets/EV_registration_cleaned.csv"

ev_df.to_csv(clean_path, index=False)

print("Clean dataset saved successfully.")
print("Shape:", ev_df.shape)

Clean dataset saved successfully.
Shape: (36, 12)

In [21]:
ev_df.head()

,State,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,Total
0,Andaman & Nicobar Island,0,20,2,36,92,23,26,64,166,117,546
1,Andhra Pradesh,1,1180,2155,1650,9681,29357,32876,56492,59842,85267,278501
2,Arunachal Pradesh,0,1,1,4,2,2,18,47,103,136,314
3,Assam,3831,7398,10859,8357,15633,40697,60786,68130,85142,83467,384300
4,Bihar,3594,8464,12380,12446,23083,55755,88223,112856,123797,119840,560438