In [1]:
# Imports and load raw data

import pandas as pd
import numpy as np

df = pd.read_csv("../data/Raw datasets/Ev_registration_bus.csv")

print("Chargers shape:", df.shape)
df.head()

Chargers shape: (37, 12)

,"Category Group (Bus), EV Type (ELECTRIC(BOV), PURE EV) Wise State Wise and Calendar Year Data for AN, AP, AR, AS, BR, CH, CG, DL, GA, GJ, HR, HP, JK, JH, KA, KL, LA, LD, MP, MH, MN, ML, MZ, NL, OR, PY, PB, RJ, SK, TN, TG, TR, DD, UP, UK, WB (2017-2026)\n\nState",2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,Total
0,Andaman & Nicobar Island,0,0,0,0,40,0,0,0,2,0,42
1,Andhra Pradesh,1,2,1,0,0,27,100,10,48,76,265
2,Arunachal Pradesh,0,0,0,0,0,0,0,0,10,2,12
3,Assam,0,0,15,0,0,0,158,70,88,45,376
4,Bihar,0,0,0,0,26,1,0,0,0,52,79

In [2]:
# Create a working copy

ev_bus_df = df.copy()

print("Original shape:", df.shape)
print("Working copy shape:", ev_bus_df.shape)

Original shape: (37, 12)
Working copy shape: (37, 12)

In [3]:
# Rename first column

ev_bus_df = ev_bus_df.rename(columns={ev_bus_df.columns[0]: "State"})

print(ev_bus_df.columns.tolist())

['State', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025', '2026', 'Total']

In [4]:
# Remove Total row

ev_bus_df = ev_bus_df[ev_bus_df["State"] != "Total"].copy()

print("Shape after removing Total row:", ev_bus_df.shape)

Shape after removing Total row: (36, 12)

In [5]:
# Check duplicate states

duplicate_states = ev_bus_df["State"].duplicated().sum()

print("Duplicate state names:", duplicate_states)

Duplicate state names: 0

In [6]:
# Check missing values

print(ev_bus_df.isnull().sum())

State    0
2017     0
2018     0
2019     0
2020     0
2021     0
2022     0
2023     0
2024     0
2025     0
2026     0
Total    0
dtype: int64

In [7]:
# Check data types

print(ev_bus_df.dtypes)

State      str
2017     int64
2018     int64
2019     int64
2020     int64
2021     int64
2022     int64
2023     int64
2024     int64
2025     int64
2026     int64
Total    int64
dtype: object

In [8]:
# Check negative values

year_cols = [str(year) for year in range(2017, 2027)]

print((ev_bus_df[year_cols] < 0).sum())

2017    0
2018    0
2019    0
2020    0
2021    0
2022    0
2023    0
2024    0
2025    0
2026    0
dtype: int64

In [9]:
# Validate Total Column

calculated_total = ev_bus_df[year_cols].sum(axis=1)

print(
    "Rows where Total does not match calculated total:",
    (ev_bus_df["Total"] != calculated_total).sum()
)

Rows where Total does not match calculated total: 0

In [10]:
# Check duplicate rows
print("Duplicate rows:", ev_bus_df.duplicated().sum())

Duplicate rows: 0

In [11]:
# Check leading/trailing whitespace

whitespace_rows = ev_bus_df[
    ev_bus_df["State"] != ev_bus_df["State"].str.strip()
]

print("State names with extra whitespace:", len(whitespace_rows))

State names with extra whitespace: 0

In [12]:
# Check blank state names

print("Blank state names:", ev_bus_df["State"].str.strip().eq("").sum())

Blank state names: 0

In [13]:
# Count zero registrations by year

print((ev_bus_df[year_cols] == 0).sum())

2017    32
2018    28
2019    21
2020    30
2021    23
2022    18
2023    17
2024    17
2025    13
2026    12
dtype: int64

In [14]:
# View rows containing at least one zero

zero_rows = ev_bus_df[
    (ev_bus_df[year_cols] == 0).any(axis=1)
]

display(
    zero_rows[["State"] + year_cols].reset_index(drop=True)
)

,State,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026
0,Andaman & Nicobar Island,0,0,0,0,40,0,0,0,2,0
1,Andhra Pradesh,1,2,1,0,0,27,100,10,48,76
2,Arunachal Pradesh,0,0,0,0,0,0,0,0,10,2
3,Assam,0,0,15,0,0,0,158,70,88,45
4,Bihar,0,0,0,0,26,1,0,0,0,52
5,Chandigarh,0,0,0,0,40,40,0,0,15,91
6,Chhattisgarh,0,0,0,0,0,0,0,0,0,0
7,Delhi,0,0,2,0,31,399,1121,1037,1382,1424
8,Goa,0,0,0,0,35,17,45,55,32,4
9,Gujarat,0,0,49,8,217,183,106,329,116,539
10,Haryana,0,2,2,2,0,0,0,21,68,83
11,Himachal Pradesh,3,29,50,0,0,0,35,0,1,295
12,Jammu and Kashmir,0,0,39,0,0,1,150,50,0,0
13,Jharkhand,0,0,0,0,0,0,2,0,0,15
14,Karnataka,0,0,0,1,28,364,270,841,446,64
15,Kerala,0,5,5,0,0,40,70,70,1,3
16,Ladakh,0,0,1,0,0,10,9,0,0,0
17,Lakshadweep,0,0,0,0,0,0,0,0,0,0
18,Madhya Pradesh,0,0,40,0,0,20,15,85,18,187
19,Manipur,0,0,0,0,0,0,0,0,0,0
20,Meghalaya,0,0,0,0,0,0,0,0,0,5
21,Mizoram,0,0,0,0,0,0,0,0,0,0
22,Nagaland,0,0,0,0,0,0,0,0,0,0
23,Odisha,0,0,0,0,0,30,21,120,209,112
24,Puducherry,0,0,0,0,0,0,0,0,25,25
25,Punjab,0,0,0,0,0,0,0,11,1,0
26,Rajasthan,0,0,0,0,0,5,6,8,14,209
27,Sikkim,0,0,0,0,0,0,0,0,0,0
28,Tamil Nadu,0,0,0,0,0,0,43,53,427,423
29,Telangana,3,9,34,2,1,0,62,348,481,182
30,Tripura,0,0,0,0,0,0,0,0,0,0
31,UT of DNH and DD,0,0,0,4,6,15,0,0,0,0
32,Uttar Pradesh,0,1,40,0,190,468,50,17,88,184
33,Uttarakhand,0,0,1,0,10,24,0,12,10,1
34,West Bengal,0,5,78,0,1,11,15,27,5,25

In [15]:
# Summary statistics

display(
    ev_bus_df[year_cols + ["Total"]].describe()
)

,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,Total
count,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000
mean,0.527778,1.638889,15.000000,2.500000,32.694444,55.305556,76.055556,113.138889,136.916667,143.000000,576.777778
std,2.090606,5.127811,34.851522,12.180781,100.909527,125.761638,201.349440,262.901845,338.450703,304.816854,1237.891574
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,4.000000,9.000000,7.500000,20.000000,172.500000
75%,0.000000,0.000000,7.500000,0.000000,14.000000,24.750000,53.000000,58.750000,73.000000,129.500000,385.250000
max,12.000000,29.000000,183.000000,73.000000,552.000000,468.000000,1121.000000,1037.000000,1442.000000,1424.000000,5396.000000

In [16]:
# Save cleaned dataset

clean_path = "../data/Cleaned datasets/Ev_registration_bus_cleaned.csv"

ev_bus_df.to_csv(clean_path, index=False)

print("Clean dataset saved successfully.")
print("Shape:", ev_bus_df.shape)

Clean dataset saved successfully.
Shape: (36, 12)

In [17]:
ev_bus_df.head()

,State,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,Total
0,Andaman & Nicobar Island,0,0,0,0,40,0,0,0,2,0,42
1,Andhra Pradesh,1,2,1,0,0,27,100,10,48,76,265
2,Arunachal Pradesh,0,0,0,0,0,0,0,0,10,2,12
3,Assam,0,0,15,0,0,0,158,70,88,45,376
4,Bihar,0,0,0,0,26,1,0,0,0,52,79