In [1]:
# Imports and load raw data

import pandas as pd
import numpy as np

df = pd.read_csv("../data/Raw datasets/Ev_registration_car.csv")

print("Chargers shape:", df.shape)
df.head()

Chargers shape: (37, 12)

,"Category Group (Four Wheeler), EV Type (ELECTRIC(BOV), PURE EV) Wise State Wise and Calendar Year Data for AN, AP, AR, AS, BR, CH, CG, DL, GA, GJ, HR, HP, JK, JH, KA, KL, LA, LD, MP, MH, MN, ML, MZ, NL, OR, PY, PB, RJ, SK, TN, TG, TR, DD, UP, UK, WB (2017-2026)\n\nState",2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,Total
0,Andaman & Nicobar Island,0,20,2,35,22,7,14,16,75,52,243
1,Andhra Pradesh,0,64,273,62,394,778,1655,4076,4942,8243,20487
2,Arunachal Pradesh,0,0,0,3,0,1,15,29,44,83,175
3,Assam,127,0,1,7,8,83,269,402,456,656,2009
4,Bihar,0,1,11,22,61,135,605,940,1136,1717,4628

In [2]:
# Create a working copy

ev_car_df = df.copy()

print("Original shape:", df.shape)
print("Working copy shape:", ev_car_df.shape)

Original shape: (37, 12)
Working copy shape: (37, 12)

In [3]:
# Rename State column

ev_car_df = ev_car_df.rename(columns={
    ev_car_df.columns[0]: "State"
})

print(ev_car_df.columns.tolist())

['State', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025', '2026', 'Total']

In [4]:
# Remove Total row

ev_car_df = ev_car_df[ev_car_df["State"] != "Total"].copy()

print("Shape after removing Total row:", ev_car_df.shape)

Shape after removing Total row: (36, 12)

In [5]:
# Check Duplicate States

print("Duplicate state names:", ev_car_df["State"].duplicated().sum())

Duplicate state names: 0

In [6]:
# Check Missing Values

print(ev_car_df.isnull().sum())

State    0
2017     0
2018     0
2019     0
2020     0
2021     0
2022     0
2023     0
2024     0
2025     0
2026     0
Total    0
dtype: int64

In [7]:
# Check data types

print(ev_car_df.dtypes)

State      str
2017     int64
2018     int64
2019     int64
2020     int64
2021     int64
2022     int64
2023     int64
2024     int64
2025     int64
2026     int64
Total    int64
dtype: object

In [8]:
# Check Negative Values

numeric_cols = ev_car_df.columns[1:]
print((ev_car_df[numeric_cols] < 0).sum())

2017     0
2018     0
2019     0
2020     0
2021     0
2022     0
2023     0
2024     0
2025     0
2026     0
Total    0
dtype: int64

In [9]:
# Validate Total Column

year_cols = [str(year) for year in range(2017, 2027)]

calculated_total = ev_car_df[year_cols].sum(axis=1)

print(
    "Rows where Total does not match calculated total:",
    (ev_car_df["Total"] != calculated_total).sum()
)

Rows where Total does not match calculated total: 0

In [10]:
# Check Duplicate Rows

print("Duplicate rows:", ev_car_df.duplicated().sum())

Duplicate rows: 0

In [11]:
print(
    "States with leading/trailing whitespace:",
    (~ev_car_df["State"].eq(ev_car_df["State"].str.strip())).sum()
)

States with leading/trailing whitespace: 0

In [12]:
print(
    "Blank State values:",
    ev_car_df["State"].str.strip().eq("").sum()
)

Blank State values: 0

In [13]:
print((ev_car_df[year_cols] == 0).sum())

2017    13
2018    12
2019    11
2020     8
2021     7
2022     5
2023     4
2024     2
2025     1
2026     0
dtype: int64

In [14]:
zero_check = ev_car_df[year_cols].eq(0)

display(
    ev_car_df.loc[
        zero_check.any(axis=1),
        ["State"] + year_cols
    ].reset_index(drop=True)
)

,State,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026
0,Andaman & Nicobar Island,0,20,2,35,22,7,14,16,75,52
1,Andhra Pradesh,0,64,273,62,394,778,1655,4076,4942,8243
2,Arunachal Pradesh,0,0,0,3,0,1,15,29,44,83
3,Assam,127,0,1,7,8,83,269,402,456,656
4,Bihar,0,1,11,22,61,135,605,940,1136,1717
5,Jammu and Kashmir,0,0,0,0,5,50,168,277,484,734
6,Ladakh,0,0,0,0,0,10,0,0,3,6
7,Lakshadweep,0,0,0,6,0,0,0,0,0,1
8,Manipur,0,0,0,0,0,1,30,77,120,95
9,Meghalaya,0,0,0,0,3,10,20,39,113,72
10,Mizoram,0,0,0,0,0,0,0,2,8,14
11,Nagaland,0,0,0,0,0,0,3,3,8,16
12,Puducherry,3,2,0,1,10,44,91,140,157,182
13,Sikkim,0,0,0,0,0,0,0,6,6,6
14,Tripura,2,0,4,0,5,0,30,39,38,35
15,UT of DNH and DD,0,0,0,2,2,16,42,62,89,75

In [15]:
# SUMMARY STATISTICS

ev_car_df.describe()

,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,Total
count,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000
mean,31.972222,49.083333,56.138889,123.305556,388.305556,1137.416667,2483.666667,2932.472222,5452.555556,6990.000000,19644.916667
std,84.921303,125.168087,116.115743,238.501850,765.244604,2273.087207,3673.182948,4022.155481,7727.576147,9582.318792,27908.814656
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,7.000000
25%,0.000000,0.000000,0.000000,1.750000,4.500000,10.000000,30.000000,56.250000,107.000000,81.000000,280.250000
50%,3.000000,7.000000,4.000000,21.000000,60.000000,187.500000,699.500000,1088.000000,1364.000000,1854.000000,5577.000000
75%,13.000000,22.750000,27.250000,106.750000,347.500000,841.250000,3172.250000,4485.250000,7348.000000,10246.750000,25850.250000
max,464.000000,636.000000,451.000000,920.000000,3732.000000,11622.000000,13712.000000,14973.000000,30587.000000,35917.000000,112093.000000

In [16]:
# Save cleaned car EV dataset

clean_path = "../data/Cleaned datasets/Ev_registration_car_cleaned.csv"

ev_car_df.to_csv(clean_path, index=False)

print("Clean dataset saved successfully.")
print("Shape:", ev_car_df.shape)

Clean dataset saved successfully.
Shape: (36, 12)

In [17]:
ev_car_df.head()

,State,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,Total
0,Andaman & Nicobar Island,0,20,2,35,22,7,14,16,75,52,243
1,Andhra Pradesh,0,64,273,62,394,778,1655,4076,4942,8243,20487
2,Arunachal Pradesh,0,0,0,3,0,1,15,29,44,83,175
3,Assam,127,0,1,7,8,83,269,402,456,656,2009
4,Bihar,0,1,11,22,61,135,605,940,1136,1717,4628